// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElMessag: typeof import('element-plus/es')['ElMessag']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
export {}
